import {
  IconBrandDiscord,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandGithub,
  IconBrandGitlab,
  IconBrandGmail,
  IconBrandMedium,
  IconBrandNotion,
  IconBrandSkype,
  IconBrandSlack,
  IconBrandStripe,
  IconBrandTelegram,
  IconBrandTrello,
  IconBrandWhatsapp,
  IconBrandZoom,
} from '@tabler/icons-react'

export const apps = [
  {
    name: 'Updating Direktori Perusahaan Pertambangan dan Energi',
    logo: <IconBrandTelegram />,
    completed: false,
    deskripsi: 'Untuk memperbarui direktori perusahaan pertambangan dan energi, sampling frame.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1XuhL54xrNJypJOALLItEUYEETd7ZsQ-6?usp=drive_link',
  },
  {
    name: 'Survei Tahunan Perusahaan Gas',
    logo: <IconBrandNotion />,
    completed: true,
    deskripsi: 'Untuk mendapatkan data yang berkaitan dengan penyediaan gas oleh perusahaan gas.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1XuhL54xrNJypJOALLItEUYEETd7ZsQ-6?usp=drive_link',
  },
  {
    name: 'Survei Tahunan Perusahaan Air Bersih',
    logo: <IconBrandFigma />,
    completed: true,
    deskripsi: 'Untuk mendapatkan data yang berkaitan dengan penyediaan air bersih oleh perusahaan air bersih tahunan.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1S20LBqpx30H0HICQnODqPhycIVvuIL4d?usp=drive_link',
  },
  {
    name: 'Survei Triwulan Perusahaan Air Bersih',
    logo: <IconBrandTrello />,
    completed: false,
    deskripsi: 'Untuk mendapatkan data yang berkaitan dengan penyediaan air bersih oleh perusahaan air bersih triwulan.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/15lMoemMiN6EzepJpperL05osuiq-jI5_?usp=drive_link',
  },
  {
    name: 'Survei Tahunan Perusahaan Listrik',
    logo: <IconBrandSlack />,
    completed: false,
    deskripsi: 'Untuk mendapatkan data yang berkaitan dengan penyediaan listrik oleh perusahaan listrik',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1Twa9MznU8jhbVf0BgANFHgA0sXd2XyjI?usp=drive_link',
  },
  {
    name: 'Survei Tahunan Perusahaan Migas',
    logo: <IconBrandZoom />,
    completed: true,
    deskripsi: 'Untuk mendapatkan data yang berkaitan dengan penyediaan migas oleh perusahaan migas.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1XhqN3Xq_CsCq2vD9EuN7MEyWGFwpUn8Y?usp=drive_link',
  },
  {
    name: 'Survei Tahunan Perusahaan Non Migas',
    logo: <IconBrandStripe />,
    completed: false,
    deskripsi: 'Untuk mendapatkan data yang berkaitan dengan penyediaan non migas oleh perusahaan non migas',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1Kin3qIrzzzRowTi8cJj3t-NP79VBySYY?usp=drive_link',
  },
  {
    name: 'Survei Captive Power',
    logo: <IconBrandGmail />,
    completed: true,
    deskripsi: 'Untuk mengumpulkan informasi mengenai kebutuhan listrik perusahaan serta listrik yang dibangkitkan sendiri oleh perusahaan.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Pertambangan dan Energi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1QedjscAH9pT9hhC2_EuUZnnvCADSQDef?usp=drive_link',
  },
  {
    name: 'Survei Perusahaan Kontruksi Triwulanan',
    logo: <IconBrandMedium />,
    completed: false,
    deskripsi: 'Untuk mengetahui perkembangan sektor konstruksi secara umum dengan referensi waktu yang lebih pendek yakni triwulanan.',
    periode: 'triwulanan',
    fungsi: 'produksi',
    kategori: 'Konstruksi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/16mGOP4QnCezrivNZFoeDeFXCvb3ej4Ai?usp=drive_link',
  },
  {
    name: 'Survei Perusahaan Kontruksi Tahunan',
    logo: <IconBrandSkype />,
    completed: false,
    deskripsi: 'Untuk mengetahui perkembangan sektor konstruksi secara umum dengan referensi waktu yang lebih panjang yakni tahunan.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Konstruksi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1_ZULc4orkRKIOh1ZUuYhOSA83ZtixYQZ?usp=drive_link',
  },
  {
    name: 'Updating Direktori Perusahaan Konstruksi',
    logo: <IconBrandDocker />,
    completed: false,
    deskripsi: 'Untuk pembaruan informasi yang terkait dengan perusahaan-perusahaan di sektor konstruksi untuk memperoleh data terkini mengenai perusahaan-perusahaan konstruksi, sebagai sampling frame survei perusahaan konstruksi.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Konstruksi',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1QlimSlNiTlsL-otHgg79SMHIH8nqMCOR?usp=drive_link',
  },
  {
    name: 'IBS Bulanan',
    logo: <IconBrandGithub />,
    completed: false,
    deskripsi: 'Untuk mendapatkan indeks produksi industri skala besar dan sedang bulanan.',
    periode: 'Bulanan',
    fungsi: 'produksi',
    kategori: 'Industri',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1uv1LVhjw3J5soWYGxFQA137jpfCFfb-y?usp=drive_link',
  },
  {
    name: 'Updating Direktori Perusahaan Awal (DPA)',
    logo: <IconBrandGitlab />,
    completed: false,
    deskripsi: 'Untuk memutakhirkan kondisi seluruh perusahaan IBS yang ada pada direktori perusahaan, sebagai sampling frame untuk SKIM & SPIM.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Industri',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1W4k_uL8r4ZkdP1edSrKJohImUx673UQC?usp=drive_link',
  },
  {
    name: 'Survei Komoditas Industri Manufaktur (KBLI 13 dan 14)',
    logo: <IconBrandDiscord />,
    completed: false,
    deskripsi: 'Untuk mengumpulkan informasi dan karakteristik industri manufaktur skala menengah dan besar dengan periode survei dilaksanakan setiap tahun sekal untuk KBLI 13 & 14 (Tekstil & Pakaian Jadi).',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Industri',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1sVV_G_1Ju7TZ00--thcV1X5DslTGQa1r?usp=drive_link',
  },
  {
    name: 'Survei Tahunan Perusahaan Industri Manufaktur (Diluar 13 & 14)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mengumpulkan informasi dan karakteristik industri manufaktur skala menengah dan besar dengan periode survei dilaksanakan setiap tahun sekali untuk KBLI diluar 13 & 14.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Industri',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1AiKrAYDqvNx3Resc1VdgFjY4adZjofCL?usp=drive_link',
  },
  {
    name: 'Laporan Pemotongan Ternak Bulanan (Simenta)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mendapatkan data jumlah ternak yang dipotong setiap bulan dan mendapatkan data rata-rata produksi hasil pemotongan ternak setiap bulan.',
    periode: 'Bulanan',
    fungsi: 'produksi',
    kategori: 'Peternakan',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1Yl1Ho7IGlZojPFv3MbPghk2kpbHsPr6h?usp=drive_link',
  },
  {
    name: 'Laporan Tahunan Perusahaan Penangkapan Ikan',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk pengumpulan data dengan subjek pendataan adalah perusahaan penangkapan ikan yang berbadan hukum dan melakukan kegiatan penangkapan ikan.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Perikanan',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1h7LttFa1HUgW5qg-TPKYjcXIdty5GkOo?usp=drive_link',
  },
  {
    name: 'Laporan Tahunan Budidaya Ikan',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk pengumpulan data dengan subyek pendataan adalah perusahaan budidaya ikan yang berbadan hukum yang melakukan kegiatan pembesaran dan/atau pembenihan ikan.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Perikanan',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/14xViKdCkXe_Vdwx_jcbyH9HIWMVYLe0W?usp=drive_link',
  },
  {
    name: 'Penangkaran Tumbuhan atau Satwa Liar',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk pengumpulan data dengan subyek pendataan adalah perusahaan yang memiliki izin penangkaran dan peredaran serta aktif melakukan kegiatan usaha penangkaran dan peredaran Tumbuhan atau Satwa Liar.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Kehutanan',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/183Re5chbGqjD3X7yLjpS3vcehZjYpjIK?usp=drive_link',
  },
  {
    name: 'Survei Pertanian Hortikultura Sayuran Buah Semusim',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk melaporkan luas dan produksi tanaman sayuran dan buah semusim dari setiap kecamatan setiap bulan.',
    periode: 'Bulanan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/15o9VQEL-IJfC7is5b7-CFm2f-iwie4In?usp=drive_link',
  },
  {
    name: 'Survei Pertanian Hortikultura Sayuran Buah Tahunan',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk melaporkan banyaknya tanaman dan produksi tanaman buah-buahan dan sayuran tahunan dari setiap kecamatan untuk setiap tahun.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1db6C2t4tK2Vhnd9AYpsoUmIXZMefIcLL?usp=drive_link',
  },
  {
    name: 'Survei Pertanian Hortikultura Sayuran Buah Triwulan',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk melaporkan banyaknya tanaman dan produksi tanaman buah-buahan dan sayuran tahunan dari setiap kecamatan, setiap triwulan.',
    periode: 'Triwulanan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1f-oxK4qEuN1Ww3nvnbvGTUACA7cTzn8V?usp=drive_link',
  },
  {
    name: 'Tanaman Hias',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk melaporkan luas dan produksi tanaman hias dari setiap kecamatan, setiap triwulan.',
    periode: 'Triwulanan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1Xm9t0VcEdbcPfSm3z4jnniuMXbVdY3mz?usp=drive_link',
  },
  {
    name: 'Tanaman Biofarmaka',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk melaporkan luas dan produksi tanaman biofarmaka dari setiap kecamatan, setiap triwulan.',
    periode: 'Triwulanan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1yHyV87stt75YAEHPuPHC8Pq8GqPq2uwI?usp=drive_link',
  },
  {
    name: 'SP Lahan',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'untuk melaporkan luas lahan menurut penggunaannya yang berada di wilayah administrasi kecamatan termasuk tanah yang diusahakan oleh rumah tangga, perusahaan, pemerintah, dan lain-lain. Data yang diisikan adalah keadaan lahan yang sebenarnya dan bukan berdasarkan status.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1bMZKR89INCexitZ77FGcMDI5M9BRql3X?usp=drive_link',
  },
  {
    name: 'SP Alat Mesin Pertanian',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk melaporkan alat/mesin pertanian dan kelembagaan pertanian yang ada di wilayah administrasi kecamatan. Alat/mesin pertanian yang dicatat adalah alat/mesin pertanian yang digunakan untuk tanaman pangan dan dikuasai oleh petani atau kelompok (kelompok tani dan kelompok UPJA), tidak termasuk yang ada ditoko. Untuk alat dan mesin pertanian yang bergerak (dapat dipindahkan) dicatat pada kecamatan domisili pemilik alat tersebut.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1M477GQzj1aM_yAb_DCK7v5sz6TuDC9Ji?usp=drive_link',
  },
  {
    name: 'SP Benih',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk melaporkan penangkaran benih (jumlah produsen benih, luaspenangkaran dan produksi benih), pengedar benih (jumlah pengedar, jumlah benih yangdiedarkan) dan jumlah penggunaan benih (bersertifikat dan tidak bersertifikat). Jumlah produsen benih dan pengedar benih yang dicatat adalah banyaknya unit usaha kondisi akhir tahun yang ada di wilayah kecamatan. Sedangkan luas penangkaran benih, produksi benih, banyaknya benih yang terjual, dan penggunaan benih dicatat selama periode Januari-Desember.',
    periode: 'Tahunan',
    fungsi: 'produksi',
    kategori: 'Hortikultura',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1fxOecmWrKklircvRdfaknV4Tv750Ei_G?usp=drive_link',
  },
  {
    name: 'Survei penyusunan disagregasi PMTB Dinas',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Sejalan dengan Rencana Kerja Pemerintah (RKP) 2024, yaitu Peningkatan Produktivitas untuk Transformasi Ekonomi yang Inklusif dan Berkelanjutan, dibutuhkan data Pembentukan Modal Tetap Bruto (PMTB) yang dirinci menurut jenis aset tetap, lapangan usaha, dan sektor institusi.',
    periode: 'Tahunan',
    fungsi: 'nerwilis',
    kategori: '',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1d7MvAga3eeeAETU6wTeWrbNgkvv3qBKJ?usp=drive_link',
  },
  {
    name: 'Survei Khusus Struktur Input Pemerintah (SKSIP)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk memperoleh keterbandingan jumlah pegawai dan balas jasa pegawai (take home pay) ASN menurut jenis pekerjaan untuk keperluan ICP Government Compensation serta untuk studi penyusunan indeks upah ASN dan Memperoleh struktur belanja bantuan sosial pemerintah daerah.',
    periode: 'Tahunan',
    fungsi: 'nerwilis',
    kategori: '',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/17UuPqyTtTL2BjzPs9VNgVJEZ5Ww-Z4L6?usp=drive_link',
  },
  {
    name: 'Survei Khusus Perusahaan Swasta non finansial (SKPS)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk memperoleh informasi mengenai : (1) Karakteristik korporasi/perusahaan swasta non-finansial, antara lain tentang jenis usaha, struktur permodalan, jumlah tenaga kerja dan sebagainya. (2) Hasil transaksi usaha Korporasi/Perusahaan Swasta Non-finansial melalui laporan keuangan perusahaan yang terdiri dari Laporan Posisi Keuangan (Balance Sheet) dan Laporan Laba Rugi (Income Statement), sehingga dapat diketahui struktur aset/harta/kekayaan, struktur pasiva (kewajiban dan modal), output, input (biaya) dan sebagainya.',
    periode: 'Tahunan',
    fungsi: 'nerwilis',
    kategori: '',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1e-Hj46zJRcG4-XLji1yBwmMCOJcvJMpi?usp=drive_link',
  },
  {
    name: 'Survei Khusus Lembaga Nonprofit Rumah Tangga (SKLNP)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Pelaksanaan survei ini dilatar belakangi akibat data aktivitas ekonomi yang komprehensif ( produksi, konsumsi, investasi) LNPRT tidak tersedia di Subject Matter BPS. Bertujuan untuk menyusun Neraca nasional sektor LNPRT dalam Full Sequence of Accounts (FSA), Benchmarking level Produk Domestik Bruto (PDB), serta Supply and Use Table LNPRT.',
    periode: 'Tahunan',
    fungsi: 'nerwilis',
    kategori: '',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1zuqHqtHWFA9fE57jCV2rtYrcIgVt88_f?usp=drive_link',
  },
  {
    name: 'Survei Khusus Lembaga Nonprofit Rumah Tangga Triwulanan (SKLNPT)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk enyusun indikator penyusunan kerangka kerja sector institusi LNPRT Indikator pendapatan dan pengeluaran LNPRT triwulanan, Pola pengeluaran konsumsi LNPRT triwulanan, dan Penambahan barang modal LNPRT triwulanan.',
    periode: 'Triwulan',
    fungsi: 'nerwilis',
    kategori: '',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1iafrqHRB6A3X9bPH2isoOI-aoHlzc-jM?usp=drive_link',
  },
  {
    name: 'Survei Khusus Studi Penyusunan Perubahan Inventori (SKSPPI)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk memperoleh gambaran mengenai kuantitas dan nilai posisi inventori/persediaan pada awal tahun dan akhir tahun.  Memperoleh pola dan struktur inventori/persediaan menurut jenis komoditas  dan klasifikasi lapangan usaha. Memperoleh informasi mengenai rasio inventori terhadap nilai produksi (output) dan  polanya pada berbagai lapangan usaha.',
    periode: 'Tahunan',
    fungsi: 'nerwilis',
    kategori: '',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/13elhjd6xbtJQTPQxdF19_MRmegAhwXk5?usp=drive_link',
  },
  {
    name: 'Survei Neraca Terintegrasi (SINASI)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Terbagi ke dalam 2 survei yaitu survei khusus neraca produksi (SKNP) dan survei khusus sektor jasa (SKSJ). SINASI digunakan untuk kebijakan pembangunan, kebutuhan indikator dan alat analisis (PDB, SUT, Tabel I-O), serta input data yang akurat, terkini, representatif, dan lengkap. SINASI bertujuan untuk mendapatkan struktur pendapatan dan struktur pengeluaran usaha serta mendapatkan rasio marketed surplus, rasio margin harga perdagangan, rasio margin pengangkutan untuk penyusunan matriks margin perdagangan dan pengangkutan (TTM).',
    periode: 'Tahunan',
    fungsi: 'nerwilis',
    kategori: '',
    pic: '340016199',
    link: 'https://drive.google.com/drive/folders/1VuYyLrNJSDE0vFkfMDSgnBJk6q6UVghC?usp=drive_link',
  },
  {
    name: 'Survei Khusus Triwulanan Neraca Produksi (SKTNP)',
    logo: <IconBrandTelegram />,
    completed: false,
    deskripsi: 'Untuk memperoleh gambaran mengenai kontribusi ekonomi hijau dalam perekonomian Indonesia baik sisi supply maupun demand.',
    pic: '340016199',
    fungsi: 'nerwilis',
    kategori: '',
    periode: 'Triwulan',
    link: 'https://drive.google.com/drive/folders/1QNirK38wOB1aVNxvZlF8prCAnvDrmZMJ?usp=sharing'
  },
  {
    name: 'SEEA',
    logo: <IconBrandNotion />,
    completed: true,
    deskripsi: 'Untuk memperoleh gambaran mengenai kontribusi ekonomi hijau dalam perekonomian Indonesia baik sisi supply maupun demand',
    pic: '340016199',
    fungsi: 'nerwilis',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/14-xOrtalhW4SusIpnND_O1eZHVkWVw4p?usp=sharing'
  },
  {
    name: 'Updating Directory',
    logo: <IconBrandFigma />,
    completed: true,
    deskripsi: 'Untuk mendapatkan populasi LNPRT by name by address dan memperbaiki klasifikasi pelaku LNPRT berdasarkan COPNI',
    pic: '340016199',
    fungsi: 'nerwilis',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1VmWcomiZEogiQVuK-XX0hlz_v53buoUI?usp=sharing'
  },
  //sosial
  {
    name: 'Survei Angkatan Kerja Nasional (Sakernas)',
    logo: <IconBrandTrello />,
    completed: false,
    deskripsi: 'Survei yang dirancang khusus untuk mengumpulkan data ketenagakerjaan. Sakernas Februari dilakukan untuk memperoleh estimasi data ketenagakerjaan yang representatif hingga tingkat provinsi. Sementara, Sakernas Agustus dilakukan untuk memperoleh estimasi data ketenagakerjaan yang representatif hingga tingkat kabupaten/kota',
    pic: '340016199',
    fungsi: 'sosial',
    kategori: '',
    periode: 'Semesteran',
    link: 'https://drive.google.com/drive/folders/1OQ3WCrXKwweHpMuLN1Ou6A4zm5x59hzK?usp=sharing'
  },
  {
    name: 'Survei Ekonomi Nasional (Susenas)',
    logo: <IconBrandSlack />,
    completed: false,
    deskripsi: 'Survei yang dirancang untuk mengumpulkan data mengenai kesejahteraan rumah tangga. Data tentang kesejahteraan rumah tangga mencakup data pendidikan, kesehatan, dan kemampuan daya beli. Susenas Maret dilakukan untuk memperoleh estimasi data hingga tingkat kabupaten/kota. Sementara, Susenas September dilakukan untuk memperoleh estimasi data hingga tingkat provinsi',
    pic: '340016199',
    fungsi: 'sosial',
    kategori: '',
    periode: 'Semesteran (Maret & September)',
    link: 'https://drive.google.com/drive/folders/1XLP7Ose1KzHvwfbREmupVvMlm4tLbvqu?usp=sharing'
  },
  {
    name: 'Survei Ekonomi Rumah Tangga Triwulanan (Seruti)',
    logo: <IconBrandZoom />,
    completed: true,
    deskripsi: 'Survei yang dirancang untuk menyusun indikator ekonomi rumah tangga secara triwulanan. Kegiatan Seruti terintegrasi dengan Susenas. Seruti menggunakan sampel yang sama dengan Susenas. Data yang dikumpulkan mencakup keterangan rumah tangga; kuantitas dan nilai konsumsi makanan, minuman, dan rokok seminggu terakhir; nilai pengeluaran bukan makanan selama sebulan dan 3 (tiga) bulan terakhir; nilai pendapatan, penerimaan, dan pengeluaran bukan konsumsi selama 3 (tiga) bulan terakhir; posisi aset dan kewajiban rumah tangga; serta persepsi terhadapkondisi ekonomi rumah tangga',
    pic: '340016199',
    fungsi: 'sosial',
    kategori: '',
    periode: 'Triwulanan (Maret, Juni, September, Desember)',
    link: 'https://drive.google.com/drive/folders/1wetf7rofoX4Exw1692rI8YlSWP_UG97C?usp=sharing'
  },
  {
    name: 'Survei Statistik Politik dan Keamanan',
    logo: <IconBrandStripe />,
    completed: false,
    deskripsi: 'Statistik yang menyajikan gambaran tentang keadaan politik dan keamanan. Keadaan politik yang dicakup meliputi komposisi kursi anggota DPRD, keterwakilan perempuan dalam kursi DPRD, dan keterlibatan perempuan dalam kepengurusan partai politik.',
    pic: '340016199',
    fungsi: 'sosial',
    kategori: '',
    periode: 'Tahunan (April)',
    link: 'https://drive.google.com/drive/folders/1Pzr9Kwembj_8GnNxin5cazBT-wAOkfCF?usp=sharing'
  },
  {
    name: 'Pendataan Potensi Desa (PODES)',
    logo: <IconBrandGmail />,
    completed: true,
    deskripsi: 'Pendataan yang dirancang untuk mendapatkan gambaran wilayah administrasi pemerintahan setingkat kelurahan di Kota Jakarta Pusat menurut potensi yang dimiliki kelurahan, ketersediaan infrastruktur di kelurahan, dan juga tantangan yang dihadapi di kelurahan. Data dan informasi yang diperoleh akan disajikan dalam tiga bagian yaitu: Potensi Kelurahan, Kerawanan Kelurahan, dan Infrastruktur di Kelurahan. Pendataan dilakukan secara sensus',
    pic: '340016199',
    fungsi: 'sosial',
    kategori: '',
    periode: 'Tahunan (Mei)',
    link: 'https://drive.google.com/drive/folders/1pYSFKeHmzVo3NZXEP_IrL78XiG34sPYb?usp=sharing'
  },
  //distribusi
  {
    name: 'Survei Harga Konsumen',
    logo: <IconBrandMedium />,
    completed: false,
    deskripsi: 'Survei yang dilakukan untuk mengetahui harga transaksi yang terjadi antara penjual (pedagang eceran) dan pembeli (konsumen). Survei Harga Konsumen digunakan sebagai dasar untuk menghitung Indeks Harga Konsumen (IHK)',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Bulanan',
    link: 'https://drive.google.com/drive/folders/1b5O5mV5qLclOO1CgX8DY9C9BmJhQAmTr?usp=sharing'
  },
  {
    name: 'Survei Harga Produsen',
    logo: <IconBrandSkype />,
    completed: false,
    deskripsi: 'Untuk memperoleh data harga produsen yang lengkap dan berkesinambungan untuk penghitungan Indeks Harga Produsen',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Bulanan',
    link: 'https://drive.google.com/drive/folders/15i9W5ozVCY56YGLyT2RN1rNCpm69ylXp?usp=sharing'
  },
  {
    name: 'Survei Harga Perdagangan Besar',
    logo: <IconBrandDocker />,
    completed: false,
    deskripsi: 'Salah satu survei rutin yang dilaksanakan oleh Badan Pusat Statistik (BPS). Tujuan survei ini adalah untuk mendapatkan data statistik Harga Perdagangan Besar yang dapat dipercaya dan tepat waktu, sehingga kita dapat melihat perkembangan harga antar waktu',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Bulanan',
    link: 'https://drive.google.com/drive/folders/1ynbuF13T1Uh8XQEPuMbWhl_dt2agMqKX?usp=sharing'
  },
  {
    name: 'Survei Tingkat Penghunian Kamar Hotel',
    logo: <IconBrandGithub />,
    completed: false,
    deskripsi: 'Survei rutin yang dilakukan setiap bulan dimana respondennya adalah hotel bintang dan hotel non bintang. Untuk hotel bintang, dilakukan secara sensus, artinya seluruh hotel didata atau didatangi petugas pencacah. Sedangkan hotel non bintang dilakukan secara survei',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Bulanan',
    link: 'https://drive.google.com/drive/folders/1as3wQRNKx6n_t6HwUAWmBW2geE7AzVFF?usp=sharing'
  },
  {
    name: 'International Comparasion Program (Kategori Makanan dan Minuman)',
    logo: <IconBrandGitlab />,
    completed: false,
    deskripsi: 'Program internasional yang diterapkan oleh dunia dengan tujuan untuk menghasilkan Paritas Daya Beli (Purchasing Power Parities/PPP) yang penting untuk mengubah ukuran kegiatan  ekonomi agar dapat dibandingkan antar negara. Bersama dengan PPP, ICP juga menghasilkan Prices  Level Indices (PLI) dan agregat Product Domestic Bruto (PDB) pengeluaran lainnya yang sebanding secara regional',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Bulanan',
    link: 'https://drive.google.com/drive/folders/1qxEhxjgRFQGnIUY8JO0lSBPz0n5HPsSz?usp=sharing'
  },
  {
    name: 'Survei Harga Kemahalan Konstruksi',
    logo: <IconBrandDiscord />,
    completed: false,
    deskripsi: 'kegiatan tahunan yang dilakukan oleh Badan Pusat Statistik (BPS) menghasilkan Indeks Kemahalan Konstruksi (IKK) yang merupakan komponen penunjang dalam kegiatan penghitungan Dana Alokasi Umum (DAU)',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Triwulanan',
    link: 'https://drive.google.com/drive/folders/1AIl5W0mLCelGcy56NQlyZuPGn4upTaer?usp=sharing'
  },
  {
    name: 'Survei Triwulanan Kegiatan Usaha',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk memantau perkembangan usaha/perusahaan yang bergerak di sektor perdagangan, pengangkutan dan komunikasi, lembaga keuangan, dan administrasi/keuangan pemerintah daerah secara triwulanan',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Triwulanan',
    link: 'https://drive.google.com/drive/folders/1QBE3FtdZ-1K6S13XQ5ky8LX43-cQAWQc?usp=sharing'
  },
  {
    name: 'International Comparison Program (Kategori Non Makanan)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Kategori Non Makanan (termasuk minuman beralkohol) dan Jasa (kecuali Pendidikan) dicacah triwulanan dengan waktu pengumpulan datanya yakni Bulan Februari, Mei, Agustus dan November',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Triwulanan',
    link: 'https://drive.google.com/drive/folders/1J_XedQwjQUiKGCl0Inigk8lOKhsLOqFJ?usp=sharing'
  },
  {
    name: 'Survei Volume Penjualan Eceran Beras',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Pendataan yang dilakukan untuk memonitor terjadinya perubahan komposisi peredaran beras di pasar akibat beberapa faktor. SVPEB dapat digunakan untuk menjawab permasalahan pemilihan jenis kualitas beras yang dapat mewakili keseluruhan beras yang ada di pasar. Survei ini bertujuan untuk mengetahui volume penjualan eceran beras menurut kualitas, daya serap pasar terhadap berbagai kualitas beras, serta peranan masing-masing pasar dalam pembentukan harga beras',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Semesteran',
    link: 'https://drive.google.com/drive/folders/1uPQ95O1NYjBGqzUPg1b4HAf49ixw4UGq?usp=sharing'
  },
  {
    name: 'Survei Restoran (VREST)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Kegiatan pendataan dengan sampel perusahaan/usaha penyedia makan minum dengan tujuan untuk memperoleh karakteristik usaha penyedia makan minum secara umum, seperti kapasitas tempat duduk, jumlah tamu/pelanggan, jumlah porsi terjual, jumlah hari kerja, jumlah tenaga kerja, pendapatan dan pengeluaran usaha serta penggunaan bahan pokok sebagai bahan baku usaha, seperti beras, daging sapi/kerbau, daging ayam, telur, dan ikan',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1Z8GnfdtLlwwj6NDsVMFX3tx-7EtQHa6A?usp=sharing'
  },
  {
    name: 'Survei Perusahaan atau Usaha Jasa Akomodasi (VHTL)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mendapatkan karakteristik usaha/perusahaan akomodasi yang mencakup profil, kegiatan, tenaga kerja, struktur pendapatan dan biaya/pengeluaran, penambahan dan pengurangan barang modal, data/informasi jumlah tamu usaha akomodasi serta keterkaitannya dengan kepemilikan modal dan lingkungan',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1MGM5XYifZAigd6hHOcjGGZiTDJELshQJ?usp=sharing'
  },
  {
    name: 'Survei Pergudangan Ekspedisi Dan Kurir (VPEK)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mendapatkan data/informasi terkait pertumbuhan sektor logistik khususnya pergudangan dan pengiriman barang (kurir/ekpedisi)',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1EJZ-lBnBGw0mWkJs4qtSooFm4wsH68T8?usp=sharing'
  },
  {
    name: 'Survei Pola Distribusi',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Dilaksanakan setiap tahun secara berkesinambungan, menggambarkan rangkaian jalur perpindahan suatu komoditas mulai dari produsen sampai ke konsumen dalam suatu wilayah',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1zJyeutrP2OB0ExScW16up3dt4-zWQuu1?usp=sharing'
  },
  {
    name: 'Survei Karakteristik Usaha',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mendapatkan data yang paling mempengaruhi perkembangan dunia usaha, yaitu teknologi informasi, inovasi, dan ketenagakerjaan',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1yZbl9MzO_q2mIP-oNyCwufIaL4Ll9avS?usp=sharing'
  },
  {
    name: 'Survei Perdagangan Antar Wilayah (SPAW)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mendapatkan nilai dan volume perdagangan antar wilayah, mendapatkan peta perdagangan peta antar wilayah, dan mengetahui moda transportasi utama yang digunakan',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1JWtTBIGjiTU02Mi4px2888ajvAakHkR-?usp=sharing'
  },
  {
    name: 'Survei E-Commerce',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Usaha yang menggunakan internet untuk menerima pesanan atau melakukan penjualan barang dan/atau jasa',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1MD-rHKJx0l9tR-o6vh4UsI50RdlSMKlC?usp=sharing'
  },
  {
    name: 'Survei Lembaga Keuangan',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'mencakup dua jenis kegiatan, yakni Pedagang Valuta Asing dan Koperasi Simpan Pinjam (KSP) serta bertujuan untuk memberikan gambaran pada pemerintah untuk memberikan kebijakan terbaik demi menyokong pertumbuhan ekonomi, salah satunya melalui lembaga keuangan koperasi',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1kMDGbSiI20srcNopXlNLBTtL-WxLRdl5?usp=sharing'
  },
  {
    name: 'Survei BUMD',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Survei yang dilakukan untuk menyusun publikasi Statistik Keuangan Badan Usaha Milik Negara (BUMN) dan Badan Usaha Milik Daerah (BUMD) yang merupakan publikasi tahunan yang diterbitkan oleh Badan Pusat Statistik. Tujuan dari publikasi ini adalah untuk menyajikan data indikator keuangan perusahaan BUMN dan BUMD di Indonesia. Indikator yang ditampilkan antara lain: nilai aset, kewajiban, ekuitas, pendapatan usaha, biaya-biaya, laba bersih, dan beberapa rasio keuangan perusahaan',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/12vTM0UNBKmmoZrIO2xBdnoz0Shnu0iyY?usp=sharing'
  },
  {
    name: 'Survei Harga Properti dan Perumahan (SHPP)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mendapatkan informasi terkait perkembangan harga dan karakteristik rumah dan apartemen, serta untuk mengetahui karakteristik perusahaan pengembang di beberapa kabupaten/kota di Indonesia. Hasil survei digunakan untuk menghitung Indeks Harga Properti Perumahan (IHPP) yang merupakan salah satu indikator untuk melihat pertumbuhan ekonomi khususnya di bidang properti',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1TSYsCPuiKSU9tA6HdVeavFdZTCg-mzIG?usp=sharing'
  },
  {
    name: 'Survei Harga Mesin dan Perkakas (SHMP)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mengamati perkembangan harga mesin dan peralatan, sebagai bahan penyusun Indeks Harga Mesin dan Peralatan, dan sebagai data persiapan untuk kegiatan International Comparison Program (ICP) 2024. SHMP 2024 diadopsi dari katalog ICP. SHMP dilaksanakan untuk mengantisipasi permintaan harga komoditas ICP',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1aitm42jKl739OrtwVUaR9AOKFzgMnp4A?usp=sharing'
  },
  {
    name: 'Survei Volume Komoditas (SVK)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Untuk mengamati volume penjualan menurut kualitas/merk komoditas yang dikonsumsi masyarakat, dan timbangan (bobot) kualitas dari beberapa komoditas.',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1qnQflUvHKA7Y6Hw8_B1kfiokyS82uK4-?usp=sharing'
  },
  {
    name: 'International Comparison Program (Jasa Pendidikan)',
    logo: <IconBrandWhatsapp />,
    completed: false,
    deskripsi: 'Kategori Jasa Pendidikan dicacah 1 (satu) kali dalam setahun',
    pic: '340016199',
    fungsi: 'distribusi',
    kategori: '',
    periode: 'Tahunan',
    link: 'https://drive.google.com/drive/folders/1sfW9PQY5HnXoLuTYiCxIZrjlu0VCD7fs?usp=sharing'
  },
]